Refactor the logic of Wait for Rancher Desktop backend

diff --git a/.github/workflows/second-test.yml b/.github/workflows/second-test.yml
--- a/.github/workflows/second-test.yml
+++ b/.github/workflows/second-test.yml
@@ -163,55 +163,51 @@ jobs:
       - name: Setup Rancher Desktop on Windows Server without GUI
         run: |
           & "C:\Program Files\Rancher Desktop\resources\resources\win32\bin\rdctl.exe" start --application.start-in-background --container-engine.name=moby --kubernetes.enabled=false
-      - name: Wait for backend
+      - name: Wait for Rancher Desktop backend
         run: |
           $deadline = (Get-Date).AddMinutes(10)
           $state = "UNKNOWN"
           $rdctlPath = "C:\Program Files\Rancher Desktop\resources\resources\win32\bin\rdctl.exe"
-          while ((Get-Date) -lt $deadline) {
-            $now = Get-Date
-            $deadlineString = $deadline.ToString("u")
-            Write-Host "Waiting for backend: ($state) $now / $deadlineString"
-            $rdProcess = Get-Process -Name "Rancher Desktop" -ErrorAction SilentlyContinue | Sort-Object -Property StartTime | Select-Object -First 1
-            if (-not $rdProcess) {
-                $state = "NOT_RUNNING"
-                Start-Sleep -Seconds 10
-                continue
-            }
-            $rdEngineJsonPath = Join-Path $env:LOCALAPPDATA "rancher-desktop\rd-engine.json"
-            if (-not (Test-Path $rdEngineJsonPath)) {
-                $state = "NO_SERVER_CONFIG"
-                Start-Sleep -Seconds 10
-                continue
-            }
-            try {
-                $apiResponse = & $rdctlPath api /v1/backend_state | ConvertFrom-Json
-                $state = $apiResponse.vmState
-            } catch {
-                $state = "NO_RESPONSE"
-            }
-            switch ($state) {
-                "ERROR" {
-                    Write-Error "Backend reached error state."
-                    exit 1
-                }
-                "STARTED" {
-                    Write-Host "PID $($rdProcess.Id) has reached state $state, accepting"
-                    exit 0
-                }
-                "DISABLED" {
-                    Write-Host "PID $($rdProcess.Id) has reached state $state, accepting"
-                    exit 0
-                }
-                default {
-                    Write-Host "Backend state: $state"
-                }
-            }
-            Start-Sleep -Seconds 10
+          $rdEngineJsonPath = Join-Path $env:LOCALAPPDATA "rancher-desktop\rd-engine.json"
+          while ((Get-Date) -lt $deadline)
+          {
+              Write-Host "Waiting for backend: ($state) $( Get-Date ) / $($deadline.ToString("u") )"
+              $rdProcess = Get-Process -Name "Rancher Desktop" -ErrorAction SilentlyContinue | Sort-Object -Property StartTime | Select-Object -First 1
+              if (-not $rdProcess)
+              {
+                  $state = "NOT_RUNNING"
+              }
+              elseif (-not (Test-Path $rdEngineJsonPath))
+              {
+                  $state = "NO_SERVER_CONFIG"
+              }
+              else
+              {
+                  try
+                  {
+                      $state = (& $rdctlPath api /v1/backend_state | ConvertFrom-Json).vmState
+                  }
+                  catch
+                  {
+                      $state = "NO_RESPONSE"
+                  }
+              }
+              switch ($state) {
+                  "ERROR" {
+                      Write-Error "Backend reached error state."
+                      exit 1
+                  }
+                  "STARTED","DISABLED" {
+                      Write-Host "PID $( $rdProcess.Id ) has reached state $state, accepting"
+                      exit 0
+                  }
+                  default {
+                      Write-Host "Backend state: $state"
+                  }
+              }
+              Start-Sleep -Seconds 10
           }
-          Write-Error "Timed out waiting for backend to stabilize."
-          Write-Error "Current time: $(Get-Date)"
-          Write-Error "Deadline: $($deadline.ToString("u"))"
+          Write-Error "Timed out waiting for backend to stabilize. Current state: $state"
           exit 1
       - name: Test Docker CLI on Windows Server without GUI
         run: |
