Test `msiexec.exe`

diff --git a/.github/workflows/second-test.yml b/.github/workflows/second-test.yml
--- a/.github/workflows/second-test.yml
+++ b/.github/workflows/second-test.yml
@@ -159,9 +159,14 @@ jobs:
           if (Test-Path $dockerDownloads) { Remove-Item $dockerDownloads -Recurse -Force }
       - name: Install Rancher Desktop on Windows Server without GUI
         run: |
-          $logPath = "$env:TEMP\MsiInstall.log"
-          winget install --id SUSE.RancherDesktop --source winget --override "/qn /norestart /l*v $logPath"
-           if (Test-Path $logPath) { cat $logPath }
+          $downloadPath = Join-Path $env:TEMP "rancher-desktop.msi"
+          try {
+              Invoke-WebRequest -Uri "https://github.com/rancher-sandbox/rancher-desktop/releases/download/v1.19.3/Rancher.Desktop.Setup.1.19.3.msi" -OutFile $downloadPath
+          } catch {
+              Write-Error "Failed to download the installer: $_"
+              exit 1
+          }          
+          & msiexec.exe /i "$downloadPath" /qn /norestart
       - name: Setup Rancher Desktop on Windows Server without GUI
         run: |
           & "C:\Program Files\Rancher Desktop\resources\resources\win32\bin\rdctl.exe" start --application.start-in-background --container-engine.name=moby --kubernetes.enabled=false
